### ISSUE TITLE
Cube concatenation failure for ocean thetao IPSL data

### ISSUE THREAD

**Issue by valeriupredoi** [ESMValGroup/ESMValCore#26]
**Describe the bug**
While running @tillku ocean heat recipe with IPSL CMIP6 data I encountered this problem:
Failure to concatenate cubeList:

```
In [4]: cubeList = iris.load("/badc/cmip6/data/CMIP6/CMIP/IPSL/IPSL-CM6A-LR/historical/r1i1p1f1/Omon/thetao/gn/latest/thetao_Omon_IPSL-CM6A-LR_his
   ...: torical_r1i1p1f1_gn_195001-201412.nc")
In [5]: cubeList                                                                                                                                  
Out[5]: 
[<iris 'Cube' of cell_area / (m2) (-- : 332; -- : 362)>,
<iris 'Cube' of sea_water_potential_temperature / (degC) (time: 780; Vertical T levels: 75; -- : 332; -- : 362)>]
In [10]: cubeList[0].var_name                                                                                                                     
Out[10]: 'area'

In [11]: cubeList[1].var_name                                                                                                                     
Out[11]: 'thetao'
```

It looks like the `thetao` variable is packaged in two separate cubes - one for the variable itself and one for the cell measures. This is not a problem for eg UKESM1 data that comes correctly cmorized eg
```
<iris 'Cube' of sea_water_potential_temperature / (degC) (time: 600; depth: 75; cell index along second dimension: 330; cell index along first dimension: 360)>
```

I am not sure what the best approach would be here: the IPSL data that I am looking at is already on ESGF so a rerun/replace of the data production will happen for a later version but not soon, so we'll have to account for this in our code before (and if they actually fix it).

**Full trace**
```
2019-05-22 12:43:55,612 UTC [14724] ERROR   Failed to run fix_metadata([<iris 'Cube' of cell_area / (m2) (-- : 332; -- : 362)>, <iris 'Cube' of sea_water_potential_temperature / (degC) (time: 780; Vertical T levels: 75; -- : 332; -- : 362)>], {'project': 'CMIP6', 'dataset': 'IPSL-CM6A-LR', 'short_name': 'thetao', 'cmor_table': 'CMIP6', 'mip': 'Omon', 'frequency': 'mon'})
2019-05-22 12:43:56,366 UTC [46729] ERROR   Program terminated abnormally, see stack trace below for more information
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/users/valeriu/anaconda3Feb19/envs/esmvaltool_new/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/users/valeriu/anaconda3Feb19/envs/esmvaltool_new/lib/python3.7/site-packages/ESMValTool-2.0a1-py3.7.egg/esmvaltool/_task.py", line 664, in _run_task
    output_files = task.run()
  File "/home/users/valeriu/anaconda3Feb19/envs/esmvaltool_new/lib/python3.7/site-packages/ESMValTool-2.0a1-py3.7.egg/esmvaltool/_task.py", line 227, in run
    self.output_files = self._run(input_files)
  File "/home/users/valeriu/anaconda3Feb19/envs/esmvaltool_new/lib/python3.7/site-packages/ESMValTool-2.0a1-py3.7.egg/esmvaltool/preprocessor/__init__.py", line 393, in _run
    product.apply(step, self.debug)
  File "/home/users/valeriu/anaconda3Feb19/envs/esmvaltool_new/lib/python3.7/site-packages/ESMValTool-2.0a1-py3.7.egg/esmvaltool/preprocessor/__init__.py", line 260, in apply
    self.cubes = preprocess(self.cubes, step, **self.settings[step])
  File "/home/users/valeriu/anaconda3Feb19/envs/esmvaltool_new/lib/python3.7/site-packages/ESMValTool-2.0a1-py3.7.egg/esmvaltool/preprocessor/__init__.py", line 202, in preprocess
    result.append(_run_preproc_function(function, items, settings))
  File "/home/users/valeriu/anaconda3Feb19/envs/esmvaltool_new/lib/python3.7/site-packages/ESMValTool-2.0a1-py3.7.egg/esmvaltool/preprocessor/__init__.py", line 188, in _run_preproc_function
    return function(items, **kwargs)
  File "/home/users/valeriu/anaconda3Feb19/envs/esmvaltool_new/lib/python3.7/site-packages/ESMValTool-2.0a1-py3.7.egg/esmvaltool/cmor/fix.py", line 109, in fix_metadata
    'fixing: %s' % cube_list)
ValueError: Cubes were not reduced to one afterfixing: 0: cell_area / (m2)                    (-- : 332; -- : 362)
1: sea_water_potential_temperature / (degC) (time: 780; Vertical T levels: 75; -- : 332; -- : 362)
```

**Comment by earnone** [comment]
Was this concatenation issue sorted out for IPSL CMIP6? I got concatenation failure testing hyint on IPSL-CM6A-LR. See  [main_log.txt](https://github.com/ESMValGroup/ESMValCore/files/4181536/main_log.txt)

**Comment by valeriupredoi** [comment]
@earnone I suspect that is a basic concatenation issue that is solved by https://github.com/ESMValGroup/ESMValCore/pull/280 - can you try with that pls :beer:

**Comment by valeriupredoi** [comment]
speaking of (cheers for bringing this issue back in the limelight @earnone ) - I lost track of what's been implemented to slve this (if any) - what's the deal with these composite cubelists? @bjlittle here is an `ncdump -h` on the file that I mention in the OP
[cellprob.txt](https://github.com/ESMValGroup/ESMValCore/files/4181970/cellprob.txt)

**Comment by earnone** [comment]
@valeriupredoi sure if I understand how... is there a line command within ESMValCore? Or any simple way to checkout `development_experiment_better_concatenation` within ESMValTool?

**Comment by valeriupredoi** [comment]
@earnone #280 has now been merged in the Core so all you have to do is to grab the latest `master` for the Core and reinstall and then you ready to test :beer:

**Comment by earnone** [comment]
Ah, easy, thanks. But nope, still failing to concatenate. The files look fine and can be concatenated with e.g.`cdo`. Both historical and ssp585 data that I am trying to concatenate go smoothly through the preprocessing individually. 

Here is the error message:
```
2020-02-13 13:16:56,433 UTC [56691] ERROR   From Cell(point=real_datetime(1850, 1, 1, 12, 0), bound=(real_datetime(1850, 1, 1, 0, 0), real_datetime(1850, 1, 2, 0, 0))) to Cell(point=real_datetime(2014, 12, 31, 12, 0), bound=(real_datetime(2014, 12, 31, 0, 0), real_datetime(2015, 1, 1, 0, 0)))

2020-02-13 13:16:56,437 UTC [56691] ERROR   From Cell(point=real_datetime(2015, 1, 1, 12, 0), bound=(real_datetime(2015, 1, 1, 0, 0), real_datetime(2015, 1, 2, 0, 0))) to Cell(point=real_datetime(2100, 12, 31, 12, 0), bound=(real_datetime(2100, 12, 31, 0, 0), real_datetime(2101, 1, 1, 0, 0)))

2020-02-13 13:16:56,437 UTC [56691] ERROR   Failed to run concatenate([<iris 'Cube' of precipitation_flux / (kg m-2 s-1) (time: 60265; latitude: 143; longitude: 144)>, <iris 'Cube' of precipitation_flux / (kg m-2 s-1) (time: 31411; latitude: 143; longitude: 144)>], {})

```

**Comment by valeriupredoi** [comment]
@earnone can you post a reduced recipe that I can use to reproduce the issue pls? :beer:

**Comment by valeriupredoi** [comment]
note that this is a different issue than the one I am reporting in the OP here

**Comment by earnone** [comment]
Great @valeriupredoi. Moved this to #490.

**Comment by zklaus** [comment]
This is related to the discussion on `cell_measures`, see eg [here](https://github.com/ESMValGroup/ESMValCore/issues/436#issuecomment-586365138) (other comments in the thread apply).

Ultimately, this is a data error in that we should remove the `area` variable.

**Comment by valeriupredoi** [comment]
I *think* this can be closed since the cell measures implementation is now fully done, and the IPSL-related issue is also closed, please reopen if need be
